apiVersion: v2
name: sample-app-1
version: 0.1.0
description: Pr pipeline for sample application-1
type: application

dependencies:
  - name: pr-pipeline
    version: 1.1.2
    repository: oci://ghcr.io/niharbabu99

